# Generated by Django 3.2.2 on 2021-05-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_auto_20210503_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='boost',
            name='boostNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='boost',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
