# Generated by Django 3.2 on 2021-05-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_auto_20210509_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boost',
            name='boostNumber',
        ),
        migrations.AddField(
            model_name='maincycle',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='boost',
            name='level',
            field=models.IntegerField(),
        ),
    ]
